title: "RuoHan Yangyang Liu Luo"
author: "RuoHan Yangyang Liu Luo"
description: "@Oxford University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: true       # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home change", icon: home}
  - {file: "README.md", title: "About me", icon: adress-card}
  - {file: "RuoHan CV", title: "CV", icon: CV}
  - {title: "About me", url: "https://www.ndcn.ox.ac.uk/team/ruohan-liu"}
  - {title: "Lab", url: "https://www.ndcn.ox.ac.uk/research/pain-and-aversive-learning"}
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:spet5872@ox.ac.uk"}
  - {title: Github, icon: github, url: "https://github.com/yangyang7755"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/yangyang7755/?hl=en"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
